# global env values
env:
  CACHIX_AUTH_TOKEN: ENCRYPTED[6ec41bc0a9aa1bb9677031de8d8b250b327028dca92b197809e7478c773570c5172e4827e5fbb6e1a7fef5546994c09b]
  CACHIX_USER: bangedorrunt
  CIRRUS_SHELL: bash -il
  DARWIN_BUILD_IMAGE: ghcr.io/cirruslabs/macos-ventura-base:latest
  LINUX_BUILD_IMAGE: nixos/nix:latest
  NIX_BUILD_FLAGS: -j auto --accept-flake-config
  NIX_INSTALL_URL: https://nixos.org/nix/install
  SUDO: sudo

build_template: &BUILD_TEMPLATE
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_TAG != "" || $CIRRUS_PR != "" || $CIRRUS_BUILD_SOURCE == ""
  name: build_${CIRRUS_OS}_${ARCH}
  timeout_in: 120m
  enable_flake_script: echo "experimental-features = nix-command flakes" | $SUDO tee -a /etc/nix/nix.conf
  install_cachix_script: nix-env -iA cachix -f https://cachix.org/api/v1/install && cachix use $CACHIX_USER
  build_script: cachix watch-exec $CACHIX_USER -- nix build $NIX_BUILD_FLAGS $OUTPUTS --system ${ARCH}-${CIRRUS_OS} --show-trace
  print_diff_script: |
    [ $CIRRUS_BRANCH = 'flakebot' ] && for out in $OUTPUTS; do
      nix build $NIX_BUILD_FLAGS $out -o result --quiet;
      nix build $NIX_BUILD_FLAGS github:bangedorrunt/nix#$(echo $out | cut -d# -f2) -o result-old --quiet;
      nix run nixpkgs#nvd -- diff ./result-old ./result;
    done || echo "Not in flakebot branch"

build_darwin_profiles_task:
  macos_instance:
    image: $DARWIN_BUILD_IMAGE
  matrix:
    - env:
        ARCH: x86_64
        OUTPUTS:
          - .#darwinConfigurations."brunetdragon@x86_64-darwin".config.system.build.toplevel
          - .#devShells.x86_64-darwin.default
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  install_nix_script: bash <(curl -L "$NIX_INSTALL_URL") --daemon
  configure_nix_script: echo -e "trusted-users = root admin\nextra-platforms = x86_64-darwin aarch64-darwin" | sudo tee -a /etc/nix/nix.conf
  kickstart_nix_daemon_script: sudo launchctl kickstart -k system/org.nixos.nix-daemon
  <<: *BUILD_TEMPLATE
# TODO generate nixOS build
