# global env values
env:
  CACHIX_AUTH_TOKEN: ENCRYPTED[6ec41bc0a9aa1bb9677031de8d8b250b327028dca92b197809e7478c773570c5172e4827e5fbb6e1a7fef5546994c09b]
  CACHIX_USER: bangedorrunt
  CIRRUS_SHELL: bash -il
  DARWIN_BUILD_IMAGE: ghcr.io/cirruslabs/macos-runner:sonoma
  LINUX_BUILD_IMAGE: nixos/nix:latest
  NIX_INSTALLER_NO_CONFIRM: "true"
  NIX_INSTALLER_TAG: "v0.19.1"
  NIX_BUILD_FLAGS: -j auto --accept-flake-config

build_template: &BUILD_TEMPLATE
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_TAG != "" || $CIRRUS_PR != "" || $CIRRUS_BUILD_SOURCE == ""
  name: build_${CIRRUS_OS}_${ARCH}
  timeout_in: 120m
  configure_cachix_script: cachix use $CACHIX_USER 
  build_script: cachix watch-exec $CACHIX_USER -- nix build $NIX_BUILD_FLAGS $OUTPUTS --system ${ARCH}-${CIRRUS_OS} --show-trace

build_darwin_profiles_task:
  macos_instance:
    image: $DARWIN_BUILD_IMAGE
  matrix:
    - env:
        ARCH: x86_64
        OUTPUTS:
          - .#darwinConfigurations."brunetdragon@macintel".config.system.build.toplevel
          # - .#devShells.x86_64-darwin.default
  install_rosetta_script: softwareupdate --install-rosetta --agree-to-license
  install_nix_script: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
  install_cachix_script: nix profile install --impure github:nixos/nixpkgs/nixpkgs-unstable#cachix
  trust_user_script: echo "trusted-users = root admin" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
  <<: *BUILD_TEMPLATE

build_pifi_profiles_task:
  matrix:
    - container:
        image: $LINUX_BUILD_IMAGE
      env:
        ARCH: arm64
        USER: root
        OUTPUTS:
          - .#nixosConfigurations."brunetdragon@pifi".config.system.build.toplevel
  <<: *BUILD_TEMPLATE
