# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "nixpkgs-fmt"
options = []
includes = ["*.nix"]
excludes = []

[formatter.lua]
command = "stylua"
options = []
includes = ["*.lua"]
excludes = []

[formatter.fennel]
command = "fnlfmt"
options = ["--fix"]
includes = ["*.fnl"]
excludes = []
