# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "alejandra"
options = []
includes = ["*.nix"]
excludes = []

# [formatter.prettier]
# command = "prettier"
# options = ["--write"]
# includes = [
#  "*.css",
#  "*.html",
#  "*.js",
#  "*.json",
#  "*.jsx",
#  "*.md",
#  "*.mdx",
#  "*.scss",
#  "*.ts",
#  "*.yaml",
# ]

[formatter.lua]
command = "stylua"
options = []
includes = ["*.lua"]
excludes = ["dotfiles/nvim/lua/*"]

[formatter.fennel]
command = "fnlfmt"
options = ["--fix"]
includes = ["*.fnl"]
excludes = []
