# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
# Formatter to run
command = "nixpkgs-fmt"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []

[formatter.lua]
# Formatter to run
command = "stylua"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.lua" ]
# Glob patterns of files to exclude
excludes = []

[formatter.fennel]
# Formatter to run
command = "fnlfmt"
# Command-line arguments for the command
options = ["--fix"]
# Glob pattern of files to include
includes = [ "*.fnl" ]
# Glob patterns of files to exclude
excludes = []
