# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.fennel]
# Formatter to run
command = "fnlfmt"
# Command-line arguments for the command
options = ["--fix"]
# Glob pattern of files to include
includes = [ "*.fnl" ]
# Glob patterns of files to exclude
excludes = []
