name: "Build flake outputs"
on:
  push:
    branches:
      - tdt
  pull_request:
    branches:
      - tdt
    types: [opened, synchronize]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
        output:
          - devShells.x86_64-darwin.default
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: bangedorrunt
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Magic Cachix
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build flake output
        run: nix build -v .#${{ matrix.output }}

        # These next steps calculate the diff between the old and new closures for a flakebot PR,
        # and posts the result for each host in a comment.
      - name: Calculate diff between closures
        # Only run if we're in a flakebot PR
        if: ${{ github.event_name == 'pull_request' && github.head_ref == 'flakebot' }}
        run: |
          nix build -v .#${{ matrix.output }} -o result-new
          nix build -v .\?ref=$(git rev-parse @~)#${{ matrix.output }} -o result-old
          echo "diff_closure<<EOF" >> $GITHUB_ENV
          # TODO remove pipe to sed when NixOS/nix#4626 is fixed
          nix store diff-closures ./result-old ./result-new | sed 's/\x1b\[[0-9;]*m//g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Post diff to PR comment
        if: ${{ github.event_name == 'pull_request' && github.head_ref == 'flakebot' }}
        uses: phulsechinmay/rewritable-pr-comment@v0.3.0
        with:
          message: |
            ### Closure diff for `${{ matrix.output }}`
            ```
            ${{ env.diff_closure }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_IDENTIFIER: closure-diff-${{ matrix.output }}
