name: Update flake inputs

on:
  schedule:
    - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
        with:
          github-token = ${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ secrets.NIX_ACCESS_TOKEN }}
          pr-title: "Nix(feat): update flake.lock"
          pr-labels: |
            dependencies
            automated
